protein = float(input('Введите количество белков в граммах: '))
fats = float(input('Введите количество жиров в граммах: '))
sugars = float(input('Введите количество углеводов в граммах: '))
kkal = (protein*4) + (fats*9) + (sugars*4)
print("Количество ккалорий в продукте:"f'{kkal}')